import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { workOnce, type SqlClient } from "../worker/graph";
import { compareReference } from "../src/packs/template-reference";
const OWNER = "99999999-9999-4999-8999-999999999999", OTHER = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
export async function runTemplateReferenceIntegration(db: SqlClient) {
  await db.query("reset role"); await db.query("insert into auth.users values($1),($2)", [OWNER, OTHER]);
  const value = async (sql: string, args: unknown[] = []) => (await db.query(sql, args)).rows[0].value;
  const role = async (id: string | null) => { await db.query(id ? "set role authenticated" : "set role anon"); await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id ?? ""]); };
  await role(OWNER); const ids: string[] = [];
  for (const name of ["a", "b", "c"]) ids.push((await value("select tn_save_source(null,$1::jsonb,null) as value", [JSON.stringify({ kind: "link", title: `Reference ${name}`, url: `https://reference-${name}.example/`, excerpt: "Synthetic reference fixture" })])).id);
  const pack = (title: string, category: string, visible = true, entries = ids.slice(0, 2)) => value("select tn_create_pack($1,'',$2,'{}',$3,$4::jsonb) as value", [title, category, visible, JSON.stringify(entries.map(source_id => ({ source_id, note: "" })))]);
  const capture = (p: string, rationale: string) => value("select tn_capture_pack_version(id,revision,'uniform-seeds-v1',$2::jsonb) as value from tn_packs where id=$1", [p, JSON.stringify([{ source_id: ids[0], rationale }])]);
  const referencePack = await pack("Independent reference", "Reference > Category"), version = await capture(referencePack, "Reference seed");
  await capture(referencePack, "Same pack is never independently scored");
  await db.query("set role tn_graph_worker"); await workOnce(db); await role(OWNER);
  const tokens = (await db.query("select p.revision,v.evidence_revision from tn_packs p join tn_pack_versions v on v.pack_id=p.id where v.id=$1", [version])).rows[0];
  const run = await value("select tn_enqueue_trust_run($1,$2,$3,$4) as value", [version, tokens.revision, tokens.evidence_revision, randomUUID()]);
  const scope = () => value("select tn_template_reference_scope($1,'Reference > Category') as value", [run.run_id]);
  await assert.rejects(scope(), e => (e as any).code === "PT409");
  await db.query("set role tn_graph_worker"); assert.equal((await workOnce(db)).state, "completed"); await role(OWNER);
  const canonical = await value("select tn_read_trust_run($1,'canonical') as value", [run.run_id]);
  assert.equal((await scope()).reference.public_readable, false);
  await role(OTHER); await assert.rejects(scope(), e => (e as any).code === "PT404");
  await role(OWNER); await db.query("select tn_publish_trust_run($1,$2,$3)", [run.run_id, tokens.revision, tokens.evidence_revision]);
  await role(OTHER); const candidatePack = await pack("Independent selection", "Reference > Category > Child", true, [ids[0], ids[2]]);
  const versions: string[] = []; for (let i = 0; i < 52; i++) versions.push(await capture(candidatePack, `Seed decision ${i}`));
  const privatePack = await pack("Private selection", "Reference > Category", false), privateVersion = await capture(privatePack, "Private seed");
  const neighbor = await pack("Outside category", "Reference > CategoryNeighbor"); await capture(neighbor, "Different category");
  await db.query("reset role"); await db.query("update tn_pack_versions set created_at='2026-09-25T12:00:00.654321Z' where id=any($1::uuid[])", [versions]);
  await role(null); const publicScope = await scope();
  assert.equal(publicScope.templates.length, 50); assert.equal(publicScope.has_more, true);
  assert.deepEqual(publicScope.templates.map((t: any) => t.id), versions.sort().reverse().slice(0, 50));
  assert(publicScope.templates.every((t: any) => t.pack_id !== referencePack && t.id !== privateVersion));
  assert.equal(publicScope.site_scores.length, 2, "all site masses, including known zero, are read");
  const compared = compareReference(publicScope); assert(compared.every(t => t.mapped_sites === 1 && t.total_sites === 2 && t.median_site_mass === 1));
  assert.equal(publicScope.reference.input_hash.length, 64); assert.equal(publicScope.reference.algorithm.methodology, "graph-trust-v1");
  await role(OTHER); assert((await scope()).templates.some((t: any) => t.id === privateVersion));
  await db.query("update tn_packs set is_public=false where id=$1", [candidatePack]);
  await role(null); const afterHide = await scope(); assert.equal(afterHide.templates.length, 0); assert.equal(afterHide.has_more, false);
  await role(OTHER); assert((await scope()).templates.some((t: any) => t.visibility_epoch === 2));
  await role(OWNER); assert.deepEqual(await value("select tn_read_trust_run($1,'canonical') as value", [run.run_id]), canonical, "comparison never rewrites graph outputs");
  await db.query("update tn_packs set is_public=false where id=$1", [referencePack]);
  await role(null); await assert.rejects(scope(), e => (e as any).code === "PT404");
  await role(OTHER); await assert.rejects(scope(), e => (e as any).code === "PT404");
  await role(OWNER); await db.query("update tn_packs set is_public=true where id=$1", [referencePack]);
  await role(null); await assert.rejects(scope(), e => (e as any).code === "PT404");
  await db.query("reset role");
  console.log("Independent reference newest-50 scope, self-pack exclusion, complete masses, RLS/revocation and graph immutability passed");
}
