import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { workOnce, type SqlClient } from "../worker/graph";
import { rankSources } from "../src/trustnode/ranking";
const OWNER = "77777777-7777-4777-8777-777777777777", OTHER = "88888888-8888-4888-8888-888888888888";
export async function runTemplateDiscoveryIntegration(db: SqlClient) {
  await db.query("reset role"); await db.query("insert into auth.users values($1),($2)", [OWNER, OTHER]);
  const value = async (sql: string, args: unknown[] = []) => (await db.query(sql, args)).rows[0].value;
  const role = async (id: string | null) => { await db.query(id ? "set role authenticated" : "set role anon"); await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id ?? ""]); };
  const discover = (category: string | null = "Discovery > Auth", next: any = null, limit = 2) => value("select tn_discover_templates($1,$2,$3,$4) as value", [category, next?.created_at ?? null, next?.id ?? null, limit]);
  await role(OWNER);
  const ids: string[] = [];
  for (const name of ["standard", "guide"]) ids.push((await value("select tn_save_source(null,$1::jsonb,null) as value", [JSON.stringify({ kind: "link", title: `Discovery ${name}`, url: `https://discovery-${name}.example/`, excerpt: "Synthetic discovery fixture" })])).id);
  const pack = async (title: string, category: string, visible = true) => value("select tn_create_pack($1,'',$2,'{}',$3,$4::jsonb) as value", [title, category, visible, JSON.stringify(ids.map(source_id => ({ source_id, note: "" })))]);
  const capture = (p: string, rationale = "Explicit synthetic seed") => value("select tn_capture_pack_version(id,revision,'uniform-seeds-v1',$2::jsonb) as value from tn_packs where id=$1", [p, JSON.stringify([{ source_id: ids[0], rationale }])]);
  const root = await pack("Discovery root", "Discovery > Auth"), version = await capture(root);
  const v2 = await capture(root, "Second immutable policy");
  const descendant = await pack("Discovery child category", "Discovery > Auth > PKCE"), v3 = await capture(descendant);
  const neighbor = await pack("Not a descendant", "Discovery > Authentication"), neighborVersion = await capture(neighbor);
  const hidden = await pack("Private discovery", "Discovery > Auth", false), hiddenVersion = await capture(hidden);
  await role(OTHER);
  const forkInfo = await value("select tn_template_fork_info($1) as value", [version]);
  const fork = await value("select tn_fork_template($1,$2,$3,$4,false,'Discovery independent fork',$5) as value", [version, forkInfo.content_hash, forkInfo.evidence_revision, forkInfo.visibility_epoch, randomUUID()]);
  await db.query("update tn_packs set is_public=true where id=$1", [fork.pack_id]);
  await db.query("reset role");
  // Equal times with microseconds force the UUID tie-break; no millisecond truncation.
  await db.query("update tn_pack_versions set created_at='2026-09-25T12:00:00.123456Z' where id=any($1::uuid[])", [[version, v2, v3, hiddenVersion, fork.version_id]]);
  await role(null);
  const first = await discover(), second = await discover(undefined, first.next);
  const expected = [version, v2, v3, fork.version_id].sort().reverse();
  assert.deepEqual([...first.templates, ...second.templates].map((t: any) => t.id), expected);
  assert.equal(second.next, null); assert.deepEqual(await discover(), first);
  assert(!JSON.stringify(first).includes(hiddenVersion)); assert(!JSON.stringify(second).includes(hiddenVersion));
  assert.equal(first.next.id, first.templates.at(-1).id, "cursor is the last returned visible row, not a hidden or lookahead row");
  assert.equal((await discover(" DISCOVERY  > Auth > PKCE ", null, 25)).templates.length, 1);
  assert(!(await discover(undefined, null, 25)).templates.some((t: any) => t.id === neighborVersion));
  assert.equal((await discover("Discovery > Missing")).templates.length, 0);
  await role(OWNER); const owned = await discover(undefined, null, 25);
  assert(owned.templates.some((t: any) => t.id === hiddenVersion));
  assert.deepEqual(owned.adoption_scope, first.adoption_scope, "private owner access does not alter public totals");
  // Changing mutable category/title cannot move or rename a saved version.
  await db.query("update tn_packs set category='Moved draft',title='New draft title' where id=$1", [root]);
  assert.equal((await discover(undefined, null, 25)).templates.find((t: any) => t.id === version).title, "Discovery root");
  await db.query("set role tn_graph_worker"); await workOnce(db); await role(OWNER);
  const compute = async () => {
    const tokens = (await db.query("select p.revision,v.evidence_revision from tn_packs p join tn_pack_versions v on v.pack_id=p.id where v.id=$1", [version])).rows[0];
    const run = await value("select tn_enqueue_trust_run($1,$2,$3,$4) as value", [version, tokens.revision, tokens.evidence_revision, randomUUID()]);
    await db.query("set role tn_graph_worker"); assert.equal((await workOnce(db)).state, "completed"); await role(OWNER);
    return { id: run.run_id, tokens, canonical: await value("select tn_read_trust_run($1,'canonical') as value", [run.run_id]) };
  };
  const baseline = await compute();
  assert.equal((await discover(undefined, null, 25)).templates.find((t: any) => t.id === version).run.public_readable, false);
  await role(null); assert.equal((await discover(undefined, null, 25)).templates.find((t: any) => t.id === version).run, null, "unpublished run existence does not leak");
  await role(OTHER);
  const counts = (await discover()).adoption_scope;
  await pack("Private extra adoption", "Discovery > Private", false);
  assert.deepEqual((await discover()).adoption_scope, counts);
  // Repeated public packs by the same curator count as packs but not extra influence.
  await pack("Repeated public adoption", "Discovery > Adoption"); await pack("Repeated public adoption 2", "Discovery > Adoption");
  const card = (await discover(undefined, null, 25)).templates.find((t: any) => t.id === version);
  const references = (await db.query("select p.id as pack_id,p.owner_id,ps.rank from tn_packs p join tn_pack_sources ps on ps.pack_id=p.id where p.is_public and ps.source_id=$1", [ids[0]])).rows;
  const existing = rankSources("standard", [{ id: ids[0], title: "standard", url: "https://discovery-standard.example/", text: "", origin: "community", earned: 0, pack_references: references as any }])[0];
  assert.equal(card.members[0].adoption.value, existing.factors.pack_adoption);
  assert.equal(card.members[0].adoption.curators, 2); assert.equal(card.members[0].adoption.value, 2);
  assert.equal(card.members[1].adoption.value, 1, "each curator's best rank-two contribution is one half");
  await role(OWNER); const after = await compute();
  assert.deepEqual(after.canonical, baseline.canonical, "discovery and adoption cannot alter the frozen graph artifact");
  await db.query("select tn_publish_trust_run($1,$2,$3)", [after.id, after.tokens.revision, after.tokens.evidence_revision]);
  await role(null); const published = (await discover(undefined, null, 25)).templates.find((t: any) => t.id === version);
  assert.equal(published.run.public_readable, true); assert.equal(published.run.site_evidence_state, "seed_only"); assert.equal(published.run.methodology, "graph-trust-v1");
  const childBefore = (await discover(undefined, null, 25)).templates.find((t: any) => t.id === fork.version_id); assert.equal(childBefore.origins.length, 1);
  await role(OWNER); await db.query("update tn_packs set is_public=false where id=$1", [root]);
  await role(null); const hiddenPage = await discover(undefined, null, 25);
  assert(!hiddenPage.templates.some((t: any) => t.id === version || t.id === v2));
  const childAfter = hiddenPage.templates.find((t: any) => t.id === fork.version_id);
  assert.deepEqual(childAfter.origins, []); assert(!JSON.stringify(childAfter).includes(root)); assert(!JSON.stringify(childAfter).includes(version));
  await role(OWNER); await db.query("update tn_packs set is_public=true where id=$1", [root]);
  await role(null); assert.equal((await discover(undefined, null, 25)).templates.find((t: any) => t.id === version).run, null, "visibility transition cannot resurrect a published run");
  await assert.rejects(discover(null, null, 26), e => (e as { code?: string }).code === "22023");
  await db.query("reset role");
  console.log("Template discovery cursor ties, category scope, RLS/provenance, capped public adoption and graph-output isolation passed");
}
